### ISSUE TITLE
Why is `confidenceMethod` inside the `credentialSubject`?

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/confidence-method-spec#9]
It feels strange to me to include the confidence method at the `credentialSubject` level when it will always be relating to the confidence in the VC and it's presentation.. not necessarily always the subject. It may of course reference the `credentialSubject`(s).

I propose we move it to the top level of the VC

**Comment by brianorwhatever** [comment]
Also noting @ottonomy made a similar comment here https://github.com/w3c-ccg/community/issues/245#issuecomment-1633210047

**Comment by dlongley** [comment]
The confidence method is meant to be "for the subject" upon which it appears. So it's a property of a particular object in the data model, for example, a VC that talks about three different people could have a confidence method for each one. It doesn't make sense for the VC itself to have a confidence method -- no verifier is trying to gain more confidence that the VC is who the VC says it is -- that's always true, the VC is in hand.

**Comment by brianorwhatever** [comment]
Yeah alright I think I'm convinced. What I had been thinking before would be that each `vc.confidenceMethod` would have a reference to a `vc.credentialSubject` that is being targeted by that particular method but that is an awkward way to look at it for a number of reasons. Having it within the `credentialSubject` makes sense to me now.
